#-------------------------------------------------------------------------------------------------------------
# Created by Damon leven (MCWertGaming) on GitHub and licenced under MIT
# for more informations visit https://github.com/mcwertgaming/archive-and-testing
#-------------------------------------------------------------------------------------------------------------
FROM archlinux/base
# install packages
RUN pacman -Syu --needed --noconfirm git cmake clang gcc make gdb
# compiler available = gcc clang
# debugger available = gdb
# build standard = cmake make