name: integration-tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  # Make Homebrew installation a little quicker
  HOMEBREW_NO_ANALYTICS: "ON"
  HOMEBREW_NO_AUTO_UPDATE: "ON"
  HOMEBREW_NO_BOTTLE_SOURCE_FALLBACK: "ON"
  HOMEBREW_NO_GITHUB_API: "ON"
  HOMEBREW_NO_INSTALL_CLEANUP: "ON"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ubuntu-20.04
        # disabled windows and macos for now, as OpenMP is not working well there
        # os: [ubuntu-20.04, macos-latest, windows-latest]

    steps:
      - name: checkout repo
        uses: actions/checkout@v1
      
      - name: build windows
        if: matrix.os == 'windows-latest'
        run: |
          ci\compile.bat

      - name: build linux
        if: matrix.os == 'ubuntu-20.04' || matrix.os == 'macos-latest'
        run: |
          bash ci/compile.sh
